# Generated by Django 4.0.2 on 2022-02-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_home_sites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='conclusion',
            field=models.TextField(blank=True),
        ),
    ]
