# Generated by Django 4.0.2 on 2022-03-18 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_languaes_web_languages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='conclusion',
            new_name='web_design',
        ),
    ]
