# Generated by Django 4.0.2 on 2022-03-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_conclusion_home_web_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='machineLearning',
            field=models.TextField(blank=True),
        ),
    ]
