# Generated by Django 4.0.2 on 2022-03-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_home_machinelearning'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='android_ios',
            field=models.TextField(blank=True),
        ),
    ]
