# Generated by Django 4.0.2 on 2022-03-23 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_review_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Web',
        ),
    ]
