# Generated by Django 4.0.2 on 2022-03-23 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_delete_web'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
    ]
